### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by tkennedy13** [mohamedfarouk/openpgp-fluentapi#2]
I have an application that is targeting .Net Framework 4.7.2. I copied the examples from [https://github.com/mohamedfarouk/openpgp-fluentapi](https://github.com/mohamedfarouk/openpgp-fluentapi). The application runs but when the code reaches this line

`var encryptedStream = encryptionTask.Run().GetEncryptedStream();`

I get this error: 

> System.IO.FileLoadException: 'Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

I have tried installing BouncyCastle and BouncyCastle.NetCore but the error remains.

Am I missing a dependency or something?

**Comment by mohamedfarouk** [comment]
> I have an application that is targeting .Net Framework 4.7.2. I copied the examples from https://github.com/mohamedfarouk/openpgp-fluentapi. The application runs but when the code reaches this line
> 
> `var encryptedStream = encryptionTask.Run().GetEncryptedStream();`
> 
> I get this error:
> 
> > System.IO.FileLoadException: 'Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
> 
> I have tried installing BouncyCastle and BouncyCastle.NetCore but the error remains.
> 
> Am I missing a dependency or something?

this seems to me as a DLL versioning issue referencing dependent BouncyCastle.NetCore library, you need first to confirm the version of nuget package BouncyCastle.NetCore referenced at your project and make sure the DLL is copied to your output directory, then try add assembly binding for BouncyCastle.Crypto  in your app/web config

**Comment by gerasvm** [comment]
> > I have an application that is targeting .Net Framework 4.7.2. I copied the examples from https://github.com/mohamedfarouk/openpgp-fluentapi. The application runs but when the code reaches this line
> > `var encryptedStream = encryptionTask.Run().GetEncryptedStream();`
> > I get this error:
> > > System.IO.FileLoadException: 'Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
> > 
> > 
> > I have tried installing BouncyCastle and BouncyCastle.NetCore but the error remains.
> > Am I missing a dependency or something?
> 
> this seems to me as a DLL versioning issue referencing dependent BouncyCastle.NetCore library, you need first to confirm the version of nuget package BouncyCastle.NetCore referenced at your project and make sure the DLL is copied to your output directory, then try add assembly binding for BouncyCastle.Crypto in your app/web config

Thank you so much, this info works for me.
