### ISSUE TITLE
Is there a way to use other SymmetricKeyAlgorithm?

### ISSUE THREAD

**Issue by norbert-olah** [mohamedfarouk/openpgp-fluentapi#4]
I see SymmetricKeyAlgorithmTag.Cast5 is used in Org.BouncyCastle.Bcpg.OpenPgp.FluentApi/PgpEncryptionTask.cs
I receive the warning: gpg: WARNING: cipher algorithm CAST5 not found in recipient preferences

**Comment by mohamedfarouk** [comment]
hi Norbert,
I have added option to parameterize the algorithm tag while building encryption task, now you can do this

`
 var encryptionTask = new PgpEncryptionBuilder()
                .Encrypt(PlainMessageStream)
                .WithArmor()
                .WithCompression()
                .WithIntegrityCheck()
                .WithSymmetricKeyAlgorithm(Org.BouncyCastle.Bcpg.SymmetricKeyAlgorithmTag.Aes256)
                .WithPublicKey(PublicKey1)
                .Build();
`

calling builder function "WithSymmetricKeyAlgorithm" accepts the algorithm tag which will be later used in encryption task
