### ISSUE TITLE
PgpEncryptionBuilder.WriteOutputTo throws exception for local file path because Uri.IsWellFormedUriString

### ISSUE THREAD

**Issue by norbert-olah** [mohamedfarouk/openpgp-fluentapi#5]
Hi!
I get a "malformed file path" error if for example `outfilePath = @"c:\folder\file.txt"`
Would be better to check path syntax with `Uri.TryCreate`.

[https://dotnetfiddle.net/zocovr](https://dotnetfiddle.net/zocovr)

**Comment by mohamedfarouk** [comment]
Honestly I don't recall what i was trying to do here by using `Uri.IsWellFormedUriString`.
anyway, I believe all we need here is to ensure the passed file path value is valid, so below values can be accepted
```

"/work/anything/something.txt" //linux like path
"work/anything/something.txt" //relative path
"./work/anything/something.txt" //relative path
"//network/work/anything/something.txt" //windows network path
"C:/work/anything/something.txt" //windows absolute path
```
